### ISSUE TITLE
Make the app single-instanced dont work

### ISSUE THREAD

**Issue by Jonty1997** [leanflutter/.github#1]
I change _windows/runner/main.cpp_ by follow the article on [https://leanflutter.org/blog/making-the-app-single-instanced](url).
but it don't work.
after i double click the xxx.exe,it still create another windows app.

this is my change,
![image](https://user-images.githubusercontent.com/57940610/201593267-ed350a82-bc35-47c6-9667-baef593a37ac.png)

**Comment by lijy91** [comment]
Did you modify the title while the application is running? If it is inconsistent with the title of main.cpp, it may cause problems.
